version: '3'

services:
  map:
    image: oobayly/openseamap-tile-server
    container_name: openseamap-tile-server
    volumes:
      - osm-data:/data/database/
      - osm-tiles:/data/tiles/
    ports:
      - 8080:80
    environment:
      - ALLOW_CORS=enabled
    command: run

volumes:
  osm-data:
    external: true
  osm-tiles:
    external: true
